import { writeFile } from "node:fs/promises";
import process from "node:process";

const SOURCE_BASE =
  "https://raw.githubusercontent.com/Campionnn/SkyShards/master";

const URLS = {
  fusionData: `${SOURCE_BASE}/public/fusion-data.json`,
  rates: `${SOURCE_BASE}/public/rates.json`,
  descriptions: `${SOURCE_BASE}/src/desc.json`
};

async function fetchJson(label, url) {
  console.log(`Downloading ${label}...`);

  const response = await fetch(url, {
    headers: {
      Accept: "application/json",
      "User-Agent": "ShardScope generator"
    }
  });

  if (!response.ok) {
    throw new Error(
      `${label} download failed: ${response.status} ${response.statusText}`
    );
  }

  return response.json();
}

function createRecipe(outputId, recipe, shardCatalog, recipeNumber) {
  const inputIds = Array.isArray(recipe.inputs)
    ? recipe.inputs
    : [];

  return {
    id: `${outputId}_RECIPE_${recipeNumber}`,
    name: `Fusion Recipe ${recipeNumber}`,

    outputAmount: Number(recipe.outputQuantity) || 1,
    isReptile: Boolean(recipe.isReptile),

    ingredients: inputIds.map((inputId) => {
      const inputShard = shardCatalog[inputId];

      if (!inputShard) {
        console.warn(
          `Warning: ${outputId} references missing shard ${inputId}`
        );
      }

      return {
        type: "shard",
        shardId: inputId,
        amount: Number(inputShard?.fuse_amount) || 1
      };
    })
  };
}

function removeMirroredRecipes(recipes) {
  const seenRecipes = new Set();

  return recipes.filter((recipe) => {
    const sortedIngredients = recipe.ingredients
      .map((ingredient) => {
        return `${ingredient.shardId}:${ingredient.amount}`;
      })
      .sort()
      .join("|");

    const duplicateKey = [
      sortedIngredients,
      recipe.outputAmount,
      recipe.isReptile
    ].join("::");

    if (seenRecipes.has(duplicateKey)) {
      return false;
    }

    seenRecipes.add(duplicateKey);
    return true;
  });
}

function convertShardData(
  fusionData,
  acquisitionRates,
  descriptions
) {
  const sourceShards = fusionData?.shards ?? {};
  const sourceRecipes = fusionData?.recipes ?? {};

  return Object.entries(sourceShards)
    .map(([sourceId, sourceShard]) => {
      const estimatedRate =
        Number(acquisitionRates?.[sourceId]) || 0;

      const description =
        descriptions?.[sourceId] ?? null;

      const rawRecipes = Array.isArray(sourceRecipes[sourceId])
        ? sourceRecipes[sourceId]
        : [];

      const convertedRecipes = rawRecipes.map(
        (recipe, recipeIndex) => {
          return createRecipe(
            sourceId,
            recipe,
            sourceShards,
            recipeIndex + 1
          );
        }
      );

      const recipes =
        removeMirroredRecipes(convertedRecipes);

      return {
        id: sourceId,

        name: sourceShard.name || sourceId,

        bazaarId: sourceShard.internal_id || null,

        classification: {
          family: sourceShard.family || null,

          rarity: sourceShard.rarity
            ? String(sourceShard.rarity).toUpperCase()
            : null,

          type: sourceShard.type || null
        },

        attribute: {
          title: description?.title || null,
          description: description?.description || null
        },

        hunting: {
          huntable: estimatedRate > 0,
          location: null,
          method: null,
          tool: null,
          difficulty: null,

          estimatedPerHour:
            estimatedRate > 0
              ? estimatedRate
              : null
        },

        fusion: {
          recipes
        },

        source: {
          project: "SkyShards",
          sourceId
        }
      };
    })
    .sort((firstShard, secondShard) => {
      return firstShard.name.localeCompare(
        secondShard.name
      );
    });
}

function buildJavaScriptFile(shards) {
  const generatedAt = new Date().toISOString();

  return `/*
  ShardScope shard database

  Automatically generated by generateShardData.mjs
  Generated at: ${generatedAt}

  This is a static database.
  ShardScope does not fetch this information at runtime.
*/

const shardData = ${JSON.stringify(shards, null, 2)};

/*
  Make the data available through window.shardData too.
  This helps if app.js accesses it through the window object.
*/
window.shardData = shardData;
`;
}

function countRecipes(shards) {
  return shards.reduce((total, shard) => {
    return total + shard.fusion.recipes.length;
  }, 0);
}

async function main() {
  console.log("");
  console.log("Starting ShardScope data generator...");
  console.log("");

  const [
    fusionData,
    acquisitionRates,
    descriptions
  ] = await Promise.all([
    fetchJson("fusion data", URLS.fusionData),
    fetchJson("acquisition rates", URLS.rates),
    fetchJson("descriptions", URLS.descriptions)
  ]);

  console.log("");
  console.log("Converting shard data...");

  const shards = convertShardData(
    fusionData,
    acquisitionRates,
    descriptions
  );

  if (shards.length === 0) {
    throw new Error(
      "The generator did not produce any shards."
    );
  }

  const outputCode = buildJavaScriptFile(shards);

  await writeFile(
    "./shardData.js",
    outputCode,
    "utf8"
  );

  const recipeCount = countRecipes(shards);

  const missingBazaarIds = shards.filter(
    (shard) => !shard.bazaarId
  ).length;

  console.log("");
  console.log("Generation complete!");
  console.log(`Shards: ${shards.length}`);
  console.log(`Recipes: ${recipeCount}`);
  console.log(
    `Missing Bazaar IDs: ${missingBazaarIds}`
  );
  console.log("");
  console.log(
    "Your existing shardData.js has been replaced."
  );
}

main().catch((error) => {
  console.error("");
  console.error("Generation failed:");
  console.error(error);
  console.error("");

  process.exitCode = 1;
});